### ISSUE TITLE
New types?

### ISSUE THREAD

**Issue by GaryJones** [Vinai/pandocfilters-php#2]
I'm trying to replicate [Leanpub block types](https://leanpub.com/help/manual#leanpub-auto-more-text-block-types), which converts 

~~~
W> Some warning text here
~~~

into a box with an icon and indented text.

I have the LaTeX for the box I want:

~~~latex
\usepackage[tikz]{bclogo}

\newcommand{\block}[3]{
  \begin{bclogo}[couleur=black!10, couleurBord=black!30, arrondi=0.30, logo={#3}, marge=10]{#1}
  {#2}
  \end{bclogo}
}

% Wrapper for above \block command
\newcommand{\warning}[2]{
  \block{#1}{#2}{\bcattention}
}
~~~

so now I'm trying to create a filter in PHP that will catch the `W>` and convert it and what follows into `\warning{...}`.

~~~php
#!/usr/bin/env php
<?php

require_once __DIR__ . '/pandocfilters.php';

Pandoc_Filter::toJSONFilter(function ($type, $value, $format, $meta) {
    if ('Str' === $type && 'W>' === $value) {
        return '\\warning{' . $value . '}';
    }
});
~~~

That isn't working, obviously, as it just echoes back the literal string instead of stating it's a LaTeX command. (For HTML generation, I presume I can return HTML, so I've left the format consideration out for now).

The python version of pandocfilters [includes](https://github.com/jgm/pandocfilters/blob/master/pandocfilters.py#L93) a general element function and then specific functions for adding in new AST types. I'd like to see pandocfilters-php include those, so I can then potentially solve my problem by creating a some type of block, and then go from there accordingly.

Any advice welcome!

**Comment by Vinai** [comment]
Just realized I haven't moved it into the stable branch, so I'll leave the issue open until then.

**Comment by Vinai** [comment]
Finally did some last pending updates and moved it to the master branch. Only took me 1.5 years.

**Comment by GaryJones** [comment]
> Only took me 1.5 years.

I wasn't in a rush :-)
