### ISSUE TITLE
PHP Fatal error:  Cannot use object of type stdClass as array

### ISSUE THREAD

**Issue by RobAley** [Vinai/pandocfilters-php#5]
Hi,

I can't get any filters to run. Trying the example ones unaltered (to make sure it's not my code!) always gives 

`pandoc /tmp/test.html -f html -t latex -o /tmp/test.pdf --filter /tmp/ucwords.php  
PHP Fatal error:  Cannot use object of type stdClass as array in /tmp/pandocfilters.php on line 90  
pandoc: Error running filter /tmp/ucwords.php  
Filter returned error status 255  `

I don't know if this is because I'm using html rather than markdown as the input format (although my assumption was this worked on pandocs internal model so input format shouldn't be an issue).

Pandoc version 1.18
PHP version 5.5.9

Any pointers or tips as to where I may be going wrong is gratefully received!

Thanks

**Comment by bumper314** [comment]
I had the same error.  I'm not sure if it's right, but changing line 90 at least got it running for me:

```
From:
        $altered = self::walk($doc, $action, $format, $doc[0]->unMeta);
To:
        $altered = self::walk($doc, $action, $format, $doc->meta);
```

**Comment by RobAley** [comment]
Thanks, that appears to work (at least in a brief test!).

**Comment by bumper314** [comment]
Better fix ("see updated post above")

**Comment by bumper314** [comment]
And incase you're looking for more examples, here's one that strips formatting from headers:

```php
#!/usr/bin/env php
<?php
require_once 'pandocfilters.php';
Pandoc_Filter::toJSONFilter(function($type, $value, $format, $meta) use ($Header, $Str) {
    if ('Header' == $type) {
      return $Header($value[0], $value[1], array($Str(Pandoc_Filter::stringify($value))));
    }
});
?>
```
